apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${K8S_NAMESPACE}

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - configmap.yaml
  - secret.yaml

images:
  - name: ${APP_NAME}
    newName: ${IMAGE_FULL}
    newTag: "${IMAGE_TAG}"