apiVersion: v1
data:
  API_URL: null
  APP_ENV: dev
  LOG_LEVEL: null
kind: ConfigMap
metadata:
  labels:
    app: hola-mundobase
    environment: dev
    managed-by: devops
  name: hola-mundobase-config
  namespace: dev-namespace
