apiVersion: v1
data:
  DB_PASSWORD: null
  DB_USER: null
kind: Secret
metadata:
  labels:
    app: hola-mundobase
    environment: dev
    managed-by: devops
  name: hola-mundobase-secrets
  namespace: dev-namespace
type: Opaque