apiVersion: v1
kind: Service
metadata:
  labels:
    app: hola-mundobase
    environment: dev
    managed-by: devops
  name: hola-mundobase-svc
  namespace: dev-namespace
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: hola-mundobase
    environment: dev
    managed-by: devops
  type: ClusterIP